Check exit status of curl
I think here is root cause of following exception:

```
ArgumentError: Invalid commit_hash: "{\"message\""
/home/runner/work/docker-images/docker-images/Rakefile:145:in `get_ruby_version_at_commit'
/home/runner/work/docker-images/docker-images/Rakefile:202:in `block (2 levels) in <top (required)>'
```